version: "3.9"

services:
  api-rest-sistema:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-rest-sistema
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "1000"
    depends_on:
      - api-postgres-sistema-chifles
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app

  api-postgres-sistema-chifles:
    image: postgres:16-alpine
    container_name: api-postgres-sistema-chifles
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sistema_chifles
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
